mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  shardingsphere:
    database:
      name: "sharding_db"
    datasource:
      names: ds-0
      ds-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:slave2;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;INIT=RUNSCRIPT FROM 'classpath:db/schema.sql'
        username: sa
        password: ""
    rules:
      sharding:
        tables:
          t_order_sharding_sphere:
            actual-data-nodes: ds-0.t_order_$->{20221010..20221011}
            tableStrategy:
              standard:
                sharding-column: create_time
                sharding-algorithm-name: lingh-interval
        sharding-algorithms:
          lingh-interval:
            type: INTERVAL
            props:
              datetime-pattern: "yyyy-MM-dd HH:mm:ss.SSS"
              datetime-lower: "2022-10-10 00:00:00.000"
              datetime-upper: "2022-10-11 23:59:59.999"
              sharding-suffix-pattern: "_yyyyMMdd"
              datetime-interval-amount: 1
              datetime-interval-unit: "DAYS"